### ISSUE TITLE
Visualize multiple robots on UI

### ISSUE THREAD

**Issue by JonasPetersenFAU** [amosproj/amos2022ss03-turtlebot-fleet-management#113]
## User story
1. As a SD
2. I want / need to visualize multiple robots on the UI with path and location
3. So that the action of all robots can easily be seen

## Acceptance criteria
* Visualize all robots in graph
* Use different colors for robots
* Display location and path of every robot

## Definition of done (DoD)
* Linter & Checker were performed and passed
* Code Review has been completed
* Code was merged in sprint release candidate
* Updates are written in issue comments
* Feature builds and tests successfully
* Acceptance by product owner
* User Story & Acceptance Criteria fulfilled

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by cat24max** [comment]
TECHNICALLY this should already work I guess. But given that we have never had 2 robots driving simultaneously, this can't be tested rn.
