### ISSUE TITLE
[FMS] Automatic recharging

### ISSUE THREAD

**Issue by JonasPetersenFAU** [amosproj/amos2022ss03-turtlebot-fleet-management#146]
## User story
1. As a SD
2. I want / need to make automatic recharging possible in the fms
3. So that the fms checks battery status of agvs the send order for recharging to the robots dependent on priority

## Acceptance criteria
* Check battery status and send order for charging under threshold
* give shortest path to next charging station
* Order abortion if battery level is too low for next order
* set agv to offline

## Definition of done (DoD)
* Linter & Checker were performed and passed
* Code Review has been completed
* Code was merged in sprint release candidate
* Updates are written in issue comments
* Feature builds and tests successfully
* Acceptance by product owner
* User Story & Acceptance Criteria fulfilled

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by Sebastian2023** [comment]
Implemented automatic recharging on fleet management side. As demonstrated in video on Slack.
