### ISSUE TITLE
Deploying service code from GitHub to RasPi

### ISSUE THREAD

**Issue by UmangBR** [amosproj/amos2022ss03-turtlebot-fleet-management#24]
## User story
1. As a SD
2. I want to deploy service code from GitHub to RasPi
3. So that whenever I commit the code in Git repository, it get's deployed in RasPi

## Acceptance criteria
* Service code deployed successfully

## Definition of done (DoD)
* Linter & Checker were performed and passed
* Code Review has been completed
* Code was merged in sprint release candidate
* Updates are written in issue comments
* Feature builds and tests successfully
* Acceptance by product owner
* User Story & Acceptance Criteria fulfilled

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by cat24max** [comment]
Config values like map and MQTT server can now be configured in config.json
This has yet to be tested with Docker
